import {
  pgTable,
  pgEnum,
  serial,
  integer,
  text,
  real,
  boolean,
  timestamp,
  jsonb,
} from "drizzle-orm/pg-core";

export const nationTypeEnum = pgEnum("nation_type", [
  "kingdom","republic","empire","federation","confederation","city_state","theocracy","monarchy","democracy","dictatorship","communist_state","socialist_state","constitutional_monarchy","parliamentary_republic","presidential_republic","custom",
]);

export const governmentTypeEnum = pgEnum("government_type", [
  "absolute_monarchy","constitutional_monarchy","parliamentary_democracy","presidential_democracy","semi_presidential","theocracy","military_junta","single_party_state","federal_republic","confederation","oligarchy","anarchy","technocracy","meritocracy","custom",
]);

export const diplomacyStatusEnum = pgEnum("diplomacy_status", [
  "neutral","allied","friendly","trade_partner","non_aggression_pact","defensive_alliance","full_alliance","hostile","war","sanctioned","embargo","trade_war","cold_war","custom",
]);

export const lawCategoryEnum = pgEnum("law_category", [
  "constitutional","civil","criminal","administrative","tax","immigration","military","environmental","labor","property","intellectual","trade","health","education","transport","custom",
]);

export const taxTypeEnum = pgEnum("tax_type", [
  "income_tax","sales_tax","property_tax","corporate_tax","value_added_tax","import_tariff","export_tariff","wealth_tax","inheritance_tax","capital_gains","excise","custom",
]);

export const passportTypeEnum = pgEnum("passport_type", [
  "ordinary","diplomatic","official","service","emergency","temporary","refugee","stateless","custom",
]);

export const electionTypeEnum = pgEnum("election_type", [
  "presidential","parliamentary","local","regional","referendum","primary","general","special","by_election","custom",
]);

export const citizenshipStatusEnum = pgEnum("citizenship_status", [
  "citizen","permanent_resident","temporary_resident","refugee","asylum_seeker","stateless","diplomat","visitor","student","worker","custom",
]);

export const creatorNationsTable = pgTable("creator_nations", {
  id: serial("id").primaryKey(),
  createdBy: integer("created_by").notNull(),
  worldId: integer("world_id"),
  name: text("name").notNull(),
  slug: text("slug"),
  description: text("description"),
  nationType: nationTypeEnum("nation_type").notNull().default("republic"),
  governmentType: governmentTypeEnum("government_type").notNull().default("parliamentary_democracy"),
  capitalCityId: integer("capital_city_id"),
  flagAssetId: integer("flag_asset_id"),
  emblemAssetId: integer("emblem_asset_id"),
  currencyCode: text("currency_code").notNull().default("USD"),
  currencySymbol: text("currency_symbol").notNull().default("$"),
  officialLanguage: text("official_language").notNull().default("en"),
  population: integer("population").notNull().default(0),
  gdp: real("gdp").notNull().default(0),
  area: real("area").notNull().default(0),
  foundingDate: timestamp("founding_date"),
  nationalAnthem: text("national_anthem"),
  motto: text("motto"),
  borders: jsonb("borders").default([]),
  regions: jsonb("regions").default([]),
  tags: jsonb("tags").default([]),
  metadata: jsonb("metadata"),
  isPublished: boolean("is_published").notNull().default(false),
  isTemplate: boolean("is_template").notNull().default(false),
  version: integer("version").notNull().default(1),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorGovernmentsTable = pgTable("creator_governments", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  name: text("name").notNull(),
  governmentType: governmentTypeEnum("government_type").notNull().default("parliamentary_democracy"),
  headOfState: text("head_of_state"),
  headOfGovernment: text("head_of_government"),
  rulingParty: text("ruling_party"),
  oppositionParty: text("opposition_party"),
  cabinetSize: integer("cabinet_size").notNull().default(15),
  parliamentSize: integer("parliament_size").notNull().default(100),
  judicialBranch: text("judicial_branch"),
  legislativeBranch: text("legislative_branch"),
  executiveBranch: text("executive_branch"),
  termLength: integer("term_length").notNull().default(4),
  lastElectionDate: timestamp("last_election_date"),
  nextElectionDate: timestamp("next_election_date"),
  approvalRating: real("approval_rating").notNull().default(50),
  stability: real("stability").notNull().default(75),
  corruptionIndex: real("corruption_index").notNull().default(0),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorMinistriesTable = pgTable("creator_ministries", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  governmentId: integer("government_id").notNull(),
  name: text("name").notNull(),
  ministryType: text("ministry_type").notNull().default("interior"),
  ministerName: text("minister_name"),
  budget: real("budget").notNull().default(0),
  employeeCount: integer("employee_count").notNull().default(100),
  responsibilities: jsonb("responsibilities").default([]),
  departments: jsonb("departments").default([]),
  headquartersBuildingId: integer("headquarters_building_id"),
  isActive: boolean("is_active").notNull().default(true),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorLawsTable = pgTable("creator_laws", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  governmentId: integer("government_id"),
  name: text("name").notNull(),
  lawCategory: lawCategoryEnum("law_category").notNull().default("civil"),
  description: text("description"),
  content: text("content"),
  articleNumber: text("article_number"),
  sectionNumber: text("section_number"),
  enactedDate: timestamp("enacted_date"),
  effectiveDate: timestamp("effective_date"),
  expiryDate: timestamp("expiry_date"),
  sponsor: text("sponsor"),
  status: text("status").notNull().default("active"),
  severity: text("severity").notNull().default("medium"),
  penalties: jsonb("penalties").default([]),
  exemptions: jsonb("exemptions").default([]),
  relatedLaws: jsonb("related_laws").default([]),
  amendments: jsonb("amendments").default([]),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorTaxRulesTable = pgTable("creator_tax_rules", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  governmentId: integer("government_id"),
  name: text("name").notNull(),
  taxType: taxTypeEnum("tax_type").notNull().default("income_tax"),
  rate: real("rate").notNull().default(0),
  bracketThresholds: jsonb("bracket_thresholds").default([]),
  exemptCategories: jsonb("exempt_categories").default([]),
  deductibleCategories: jsonb("deductible_categories").default([]),
  collectionFrequency: text("collection_frequency").notNull().default("monthly"),
  enforcementLevel: text("enforcement_level").notNull().default("standard"),
  penalties: jsonb("penalties").default([]),
  effectiveDate: timestamp("effective_date"),
  expiryDate: timestamp("expiry_date"),
  isActive: boolean("is_active").notNull().default(true),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorElectionsTable = pgTable("creator_elections", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  governmentId: integer("government_id"),
  name: text("name").notNull(),
  electionType: electionTypeEnum("election_type").notNull().default("parliamentary"),
  scheduledDate: timestamp("scheduled_date").notNull(),
  actualDate: timestamp("actual_date"),
  status: text("status").notNull().default("scheduled"),
  eligibleVoters: integer("eligible_voters").notNull().default(0),
  totalVotes: integer("total_votes").notNull().default(0),
  turnoutPercentage: real("turnout_percentage").notNull().default(0),
  candidates: jsonb("candidates").default([]),
  parties: jsonb("parties").default([]),
  results: jsonb("results").default({}),
  winner: text("winner"),
  runnerUp: text("runner_up"),
  isRunoffRequired: boolean("is_runoff_required").notNull().default(false),
  runoffDate: timestamp("runoff_date"),
  votingMethod: text("voting_method").notNull().default("first_past_post"),
  constituencyIds: jsonb("constituency_ids").default([]),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorPoliticalPartiesTable = pgTable("creator_political_parties", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  name: text("name").notNull(),
  acronym: text("acronym"),
  ideology: text("ideology"),
  description: text("description"),
  leader: text("leader"),
  foundedDate: timestamp("founded_date"),
  memberCount: integer("member_count").notNull().default(0),
  seatsInParliament: integer("seats_in_parliament").notNull().default(0),
  approvalRating: real("approval_rating").notNull().default(0),
  color: text("color").notNull().default("#000000"),
  logoAssetId: integer("logo_asset_id"),
  manifesto: text("manifesto"),
  policies: jsonb("policies").default([]),
  isRulingParty: boolean("is_ruling_party").notNull().default(false),
  isOppositionParty: boolean("is_opposition_party").notNull().default(false),
  isActive: boolean("is_active").notNull().default(true),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorCitizenshipsTable = pgTable("creator_citizenships", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  npcId: integer("npc_id"),
  status: citizenshipStatusEnum("citizenship_status").notNull().default("citizen"),
  grantedDate: timestamp("granted_date").notNull().defaultNow(),
  expiryDate: timestamp("expiry_date"),
  birthDate: timestamp("birth_date"),
  placeOfBirth: text("place_of_birth"),
  naturalizationDate: timestamp("naturalization_date"),
  passportNumber: text("passport_number"),
  nationalIdNumber: text("national_id_number"),
  taxIdNumber: text("tax_id_number"),
  votingRights: boolean("voting_rights").notNull().default(true),
  militaryService: boolean("military_service").notNull().default(false),
  canHoldPublicOffice: boolean("can_hold_public_office").notNull().default(true),
  dualCitizenshipAllowed: boolean("dual_citizenship_allowed").notNull().default(false),
  otherCitizenships: jsonb("other_citizenships").default([]),
  restrictions: jsonb("restrictions").default([]),
  benefits: jsonb("benefits").default([]),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorPassportsTable = pgTable("creator_passports", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  citizenshipId: integer("citizenship_id").notNull(),
  passportNumber: text("passport_number").notNull().unique(),
  passportType: passportTypeEnum("passport_type").notNull().default("ordinary"),
  fullName: text("full_name").notNull(),
  dateOfBirth: timestamp("date_of_birth").notNull(),
  placeOfBirth: text("place_of_birth"),
  gender: text("gender"),
  nationality: text("nationality").notNull(),
  issueDate: timestamp("issue_date").notNull().defaultNow(),
  expiryDate: timestamp("expiry_date").notNull(),
  issuingAuthority: text("issuing_authority").notNull(),
  photoAssetId: integer("photo_asset_id"),
  signatureAssetId: integer("signature_asset_id"),
  visaPages: integer("visa_pages").notNull().default(32),
  usedVisaPages: integer("used_visa_pages").notNull().default(0),
  isBiometric: boolean("is_biometric").notNull().default(true),
  isActive: boolean("is_active").notNull().default(true),
  isLost: boolean("is_lost").notNull().default(false),
  isStolen: boolean("is_stolen").notNull().default(false),
  reportedLostDate: timestamp("reported_lost_date"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorVisasTable = pgTable("creator_visas", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  passportId: integer("passport_id").notNull(),
  visaType: text("visa_type").notNull().default("tourist"),
  visaNumber: text("visa_number").notNull(),
  purpose: text("purpose").notNull(),
  entryCount: text("entry_count").notNull().default("single"),
  validFrom: timestamp("valid_from").notNull(),
  validUntil: timestamp("valid_until").notNull(),
  durationOfStay: integer("duration_of_stay").notNull().default(90),
  issuingCountry: text("issuing_country").notNull(),
  issuingAuthority: text("issuing_authority").notNull(),
  restrictions: jsonb("restrictions").default([]),
  conditions: jsonb("conditions").default([]),
  isUsed: boolean("is_used").notNull().default(false),
  entryDate: timestamp("entry_date"),
  exitDate: timestamp("exit_date"),
  overstayed: boolean("overstayed").notNull().default(false),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorBordersTable = pgTable("creator_borders", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  adjacentNationId: integer("adjacent_nation_id"),
  name: text("name").notNull(),
  borderType: text("border_type").notNull().default("land"),
  length: real("length").notNull().default(0),
  points: jsonb("points").notNull().default([]),
  isControlled: boolean("is_controlled").notNull().default(true),
  isDisputed: boolean("is_disputed").notNull().default(false),
  disputeStatus: text("dispute_status"),
  militarized: boolean("militarized").notNull().default(false),
  fortificationLevel: text("fortification_level").notNull().default("none"),
  crossingPoints: jsonb("crossing_points").default([]),
  naturalFeatures: jsonb("natural_features").default([]),
  treaties: jsonb("treaties").default([]),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorBorderCheckpointsTable = pgTable("creator_border_checkpoints", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  borderId: integer("border_id").notNull(),
  name: text("name").notNull(),
  checkpointType: text("checkpoint_type").notNull().default("land"),
  posX: real("pos_x").notNull().default(0),
  posY: real("pos_y").notNull().default(0),
  posZ: real("pos_z").notNull().default(0),
  buildingId: integer("building_id"),
  capacity: integer("capacity").notNull().default(100),
  operatingHours: text("operating_hours").notNull().default("00:00-24:00"),
  isOpen: boolean("is_open").notNull().default(true),
  requiredDocuments: jsonb("required_documents").default([]),
  visaRequired: boolean("visa_required").notNull().default(true),
  visaTypes: jsonb("visa_types").default([]),
  inspectionLevel: text("inspection_level").notNull().default("standard"),
  averageWaitTime: real("average_wait_time").notNull().default(15),
  staffCount: integer("staff_count").notNull().default(10),
  hasScanner: boolean("has_scanner").notNull().default(true),
  hasXray: boolean("has_xray").notNull().default(true),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorDiplomaticRelationsTable = pgTable("creator_diplomatic_relations", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  targetNationId: integer("target_nation_id").notNull(),
  status: diplomacyStatusEnum("diplomacy_status").notNull().default("neutral"),
  establishedDate: timestamp("established_date").notNull().defaultNow(),
  embassyLevel: text("embassy_level").notNull().default("none"),
  hasEmbassy: boolean("has_embassy").notNull().default(false),
  hasConsulate: boolean("has_consulate").notNull().default(false),
  ambassador: text("ambassador"),
  diplomaticStaff: integer("diplomatic_staff").notNull().default(0),
  tradeAgreement: boolean("trade_agreement").notNull().default(false),
  tradeVolume: real("trade_volume").notNull().default(0),
  nonAggressionPact: boolean("non_aggression_pact").notNull().default(false),
  defensiveAlliance: boolean("defensive_alliance").notNull().default(false),
  fullAlliance: boolean("full_alliance").notNull().default(false),
  sanctions: jsonb("sanctions").default([]),
  embargo: boolean("embargo").notNull().default(false),
  visaWaiver: boolean("visa_waiver").notNull().default(false),
  trustLevel: real("trust_level").notNull().default(50),
  tensionLevel: real("tension_level").notNull().default(0),
  notes: text("notes"),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorTreatiesTable = pgTable("creator_treaties", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  treatyType: text("treaty_type").notNull().default("trade"),
  signatories: jsonb("signatories").notNull().default([]),
  signedDate: timestamp("signed_date").notNull(),
  effectiveDate: timestamp("effective_date"),
  expiryDate: timestamp("expiry_date"),
  status: text("status").notNull().default("draft"),
  content: text("content"),
  terms: jsonb("terms").default([]),
  obligations: jsonb("obligations").default([]),
  benefits: jsonb("benefits").default([]),
  penalties: jsonb("penalties").default([]),
  ratificationStatus: jsonb("ratification_status").default({}),
  amendments: jsonb("amendments").default([]),
  isMultilateral: boolean("is_multilateral").notNull().default(false),
  isSecret: boolean("is_secret").notNull().default(false),
  documentAssetId: integer("document_asset_id"),
  createdBy: integer("created_by").notNull(),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorNationTemplatesTable = pgTable("creator_nation_templates", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  nationType: nationTypeEnum("nation_type").notNull().default("republic"),
  governmentType: governmentTypeEnum("government_type").notNull().default("parliamentary_democracy"),
  payload: jsonb("payload").notNull().default({}),
  isGlobal: boolean("is_global").notNull().default(false),
  createdBy: integer("created_by").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorNationVersionsTable = pgTable("creator_nation_versions", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  version: integer("version").notNull(),
  snapshot: jsonb("snapshot").notNull().default({}),
  changelog: text("changelog"),
  createdBy: integer("created_by").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const creatorNationHistoryTable = pgTable("creator_nation_history", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  action: text("action").notNull(),
  entityType: text("entity_type").notNull().default("nation"),
  entityId: integer("entity_id"),
  performedBy: integer("performed_by").notNull(),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const creatorNationStatisticsTable = pgTable("creator_nation_statistics", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  totalGovernments: integer("total_governments").notNull().default(0),
  totalPopulation: integer("total_population").notNull().default(0),
  totalCitizens: integer("total_citizens").notNull().default(0),
  totalResidents: integer("total_residents").notNull().default(0),
  totalCities: integer("total_cities").notNull().default(0),
  totalBorders: integer("total_borders").notNull().default(0),
  totalDiplomaticRelations: integer("total_diplomatic_relations").notNull().default(0),
  totalTreaties: integer("total_treaties").notNull().default(0),
  totalLaws: integer("total_laws").notNull().default(0),
  totalMinistries: integer("total_ministries").notNull().default(0),
  totalPoliticalParties: integer("total_political_parties").notNull().default(0),
  gdp: real("gdp").notNull().default(0),
  gdpPerCapita: real("gdp_per_capita").notNull().default(0),
  taxRevenue: real("tax_revenue").notNull().default(0),
  governmentApproval: real("government_approval").notNull().default(50),
  politicalStability: real("political_stability").notNull().default(75),
  corruptionIndex: real("corruption_index").notNull().default(0),
  militaryStrength: real("military_strength").notNull().default(0),
  happinessIndex: real("happiness_index").notNull().default(50),
  metadata: jsonb("metadata"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const creatorNationExportsTable = pgTable("creator_nation_exports", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  format: text("format").notNull().default("json"),
  payload: jsonb("payload").notNull().default({}),
  checksum: text("checksum"),
  exportedBy: integer("exported_by").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const creatorNationRuntimeTable = pgTable("creator_nation_runtime", {
  id: serial("id").primaryKey(),
  nationId: integer("nation_id").notNull(),
  isSimulating: boolean("is_simulating").notNull().default(false),
  simulationTick: integer("simulation_tick").notNull().default(0),
  governmentStability: real("government_stability").notNull().default(75),
  economyHealth: real("economy_health").notNull().default(50),
  civilUnrestLevel: real("civil_unrest_level").notNull().default(0),
  electionCycleProgress: real("election_cycle_progress").notNull().default(0),
  taxCollectionRate: real("tax_collection_rate").notNull().default(0),
  borderSecurityLevel: real("border_security_level").notNull().default(50),
  diplomaticTension: real("diplomatic_tension").notNull().default(0),
  activeWars: integer("active_wars").notNull().default(0),
  activeTreaties: integer("active_treaties").notNull().default(0),
  migrationRate: real("migration_rate").notNull().default(0),
  populationGrowth: real("population_growth").notNull().default(0),
  inflationRate: real("inflation_rate").notNull().default(0),
  unemploymentRate: real("unemployment_rate").notNull().default(0),
  metadata: jsonb("metadata"),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});
